CONFIG_FOLDER: configs
FOLDER: '${oc.env:SOKE_DATA_ROOT,.}/experiments'

TEST:
  FOLDER: results

DATASET:
  TASK_ROOT: '${oc.env:SOKE_DATA_ROOT,.}/deps/mGPT_instructions'
  SMPL_PATH: '${oc.env:SOKE_DATA_ROOT,.}/deps/smpl'
  TRANSFORM_PATH: '${oc.env:SOKE_DATA_ROOT,.}/deps/transforms/'
  WORD_VERTILIZER_PATH: '${oc.env:SOKE_DATA_ROOT,.}/deps/t2m/glove/'
  KIT:
    ROOT: '${oc.env:SOKE_DATA_ROOT,.}/datasets/kit-ml'
    SPLIT_ROOT: '${oc.env:SOKE_DATA_ROOT,.}/datasets/kit-ml'
    MEAN_STD_PATH: '${oc.env:SOKE_DATA_ROOT,.}/deps/t2m/'
  HUMANML3D:
    ROOT: '${oc.env:SOKE_DATA_ROOT,.}/datasets/humanml3d'
    SPLIT_ROOT: '${oc.env:SOKE_DATA_ROOT,.}/datasets/humanml3d'
    MEAN_STD_PATH: '${oc.env:SOKE_DATA_ROOT,.}/deps/t2m/'

METRIC:
  TM2T:
    t2m_path: '${oc.env:SOKE_DATA_ROOT,.}/deps/t2m/'

model:
  whisper_path: '${oc.env:SOKE_DATA_ROOT,.}/deps/whisper-large-v2'

RENDER:
  BLENDER_PATH: libs/blender-2.93.2-linux-x64/blender
  SMPL_MODEL_PATH: '${oc.env:SOKE_DATA_ROOT,.}/deps/smpl/smpl_models/smpl'
  MODEL_PATH: '${oc.env:SOKE_DATA_ROOT,.}/deps/smpl/smpl_models/'
  FACES_PATH: '${oc.env:SOKE_DATA_ROOT,.}/deps/smplh/smplh.faces'
