CONFIG_FOLDER: configs # Config files path
FOLDER: experiments # Experiment files saving path

TEST:
  FOLDER: results # Testing files saving path

DATASET:
  TASK_ROOT: ./prepare/instructions
  SMPL_PATH: ./smpl-x
  TRANSFORM_PATH: ./deps/transforms/
  # Word vectorizer (glove) - LOCAL PATH
  WORD_VERTILIZER_PATH: ./glove/
  KIT:
    ROOT: datasets/kit-ml
    SPLIT_ROOT: datasets/kit-ml
    MEAN_STD_PATH: ./deps/t2m/
  HUMANML3D:
    ROOT: datasets/humanml3d
    SPLIT_ROOT: datasets/humanml3d
    MEAN_STD_PATH: ./deps/t2m/

METRIC:
  TM2T:
    # Disable t2m metrics for now (not critical for training)
    t2m_path: ./deps/t2m/

model:
  whisper_path: ./deps/whisper-large-v2

RENDER:
  BLENDER_PATH: blender
  SMPL_MODEL_PATH: ./smpl-x
  MODEL_PATH: ./smpl-x
  FACES_PATH: ./smpl-x/smplh.faces

