NAME: SOKE # Experiment names
ACCELERATOR: 'gpu' # Devices optioncal: “cpu”, “gpu”, “tpu”, “ipu”, “hpu”, “mps, “auto”
NUM_NODES: 1 # Number of GPU nodes for distributed training
# DEVICE: [0,1,2,3,4,5] # Index of gpus eg. [0] or [0,1,2,3]
DEVICE: [0] # for my current setup a single gpu

TRAIN:
  #---------------------------------
  STAGE: lm_pretrain # stage "vae" , "lm_pretrain", "lm_instruct"
  #---------------------------------
  # NUM_WORKERS: 16 # Number of workers
  NUM_WORKERS: 2 # reduced to 2 for pc limitations
  BATCH_SIZE: 8 # Size of batches
  END_EPOCH: 150 # End epoch (Soke default)
  RESUME: '${oc.env:SOKE_DATA_ROOT,.}/experiments/mgpt/SOKE'
  PRETRAINED: '${oc.env:SOKE_DATA_ROOT,.}/experiments/mgpt/SOKE'
  PRETRAINED_VAE: '${oc.env:SOKE_DATA_ROOT,.}/experiments/mgpt/DETO/checkpoints/last.ckpt'

  OPTIM:
    target: AdamW
    params:
      lr: 2e-4
      betas: [0.9, 0.99]
      weight_decay: 0.0
  
  LR_SCHEDULER:
    target: CosineAnnealingLR
    params:
      T_max: ${TRAIN.END_EPOCH}  #${eval:${LOGGER.VAL_EVERY_STEPS} * 100}
      eta_min: 1e-6

# Evaluating Configuration
EVAL:
  # BATCH_SIZE: 8 # Evaluating Batch size
  BATCH_SIZE: 8
  SPLIT: val
  NUM_WORKERS: 2 # Reduced from default 16 to prevent Windows page file exhaustion (error 1455)

TEST:
  CHECKPOINTS: null
  SPLIT: test
  # BATCH_SIZE: 8 # training Batch size
  BATCH_SIZE: 24
  NUM_WORKERS: 8 # Set to 0 to prevent Windows DataLoader worker deadlocks
  REPLICATION_TIMES: 1 # Number of times to replicate the test
  SAVE_PREDICTIONS: TRUE # was false

DATASET:
  target: mGPT.data.H2S.H2SDataModule
  H2S:
    DATASET_NAME: how2sign_csl_phoenix_isharah
    ROOT: '${oc.env:SOKE_DATA_ROOT,.}/data/How2Sign'
    CSL_ROOT: '${oc.env:SOKE_DATA_ROOT,.}/data/CSL-Daily'
    PHOENIX_ROOT: '${oc.env:SOKE_DATA_ROOT,.}/data/Phoenix_2014T'
    ISHARAH_ROOT: '${oc.env:SOKE_DATA_ROOT,.}/data/Isharah'
    MEAN_PATH: '${oc.env:SOKE_DATA_ROOT,.}/deps/mean.pt'
    STD_PATH: '${oc.env:SOKE_DATA_ROOT,.}/deps/std.pt'
    MAX_MOTION_LEN: 400
    MIN_MOTION_LEN: 40
    MAX_TEXT_LEN: 40
    PICK_ONE_TEXT: true
    FRAME_RATE: 20.0
    UNIT_LEN: 4
    STD_TEXT: False
  CODE_PATH: TOKENS_h2s_csl_phoenix_isharah

METRIC:
  TYPE: ['TM2TMetrics']

LOSS:
  LAMBDA_FEATURE: 1.0
  LAMBDA_VELOCITY: 0.0
  LAMBDA_COMMIT: 0.02
  LAMBDA_CLS: 1.0
  ABLATION:
    RECONS_LOSS: 'l1_smooth'

model:
  target: mGPT.models.mgpt.MotionGPT
  params:
    condition: 'text'
    task: 't2m'
    lm: ${lm.mbart_h2s_csl_phoenix_isharah}
    motion_vae: ${vq.re96}
    hand_vae_cfg: ${vq.hand192}
    rhand_vae_cfg: ${vq.hand192}

LOGGER:
  TYPE: ['wandb']
  VAL_EVERY_STEPS: 10
  WANDB:
    params:
      project: SLG